### ISSUE TITLE
installation instructions 

### ISSUE THREAD

**Issue by mfastudillo** [BONSAMURAIS/ystafdb#2]
Hi!

are the lines 

```
pipenv install
pipenv shell
```
in the installation instructions needed? 

I would just assume the user already has a virtual environment with other (bonsai) tools. and propose to activate it before installing.

**Comment by kuzeko** [comment]
@IKnowLogic what do you think?
Maybe we can just say "if you have ... then activate" "otherwise... "

**Comment by tngTUDOR** [comment]
the virtual environment part is now gone ;) from the documentation.
