### ISSUE TITLE
missing deps on cli

### ISSUE THREAD

**Issue by tngTUDOR** [BONSAMURAIS/ystafdb#3]
Current:

when installing a clone of the repo and issuing:

```
python setup.py install
```

running the cli fails with a missing dependency error:
```
File "/home/jasonjason/miniconda3/envs/ystafdb/lib/python3.8/site-packages/ystafdb-0.4-py3.8.egg/ystafdb/graph_common.py", line 3, in <module>
ModuleNotFoundError: No module named 'rdflib'

```

The following dependencies are also missing:

- rdflib
- pandas

**Comment by kuzeko** [comment]
This has been fixed by 
https://github.com/BONSAMURAIS/ystafdb/commit/e22099cbbbda2d559fab6a7d70c081f505df1316
